# Generated by Django 3.1.2 on 2021-02-04 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('discription', models.TextField(max_length=3000, verbose_name='Discription')),
                ('pictures', models.ImageField(upload_to='post/', verbose_name='Pictures')),
                ('1', models.IntegerField(verbose_name='1')),
                ('group', models.CharField(choices=[('Base', 'base'), ('Premium', 'premium'), ('VIP', 'vip')], default='base', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.CharField(max_length=3000, verbose_name='Discription')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
        ),
    ]
